### ISSUE TITLE
Translate context when importing common JS modules.

### ISSUE THREAD

**Issue by CrowdHailer** [rollup/rollup-plugin-commonjs#31]
I have not done enough research on this problem to explain why so I will just start with an example.
```js
import D3 from 'd3';

console.log(D3);
```
This code throws the error because the document object cannot be found on the this context. 

This translator might need to set the global context of the import as the window as opposed to leaving it undefined per es6 modules.

**Comment by Rich-Harris** [comment]
Thanks – fixed in 2.2.0

**Comment by CrowdHailer** [comment]
This example with D3 still does not work. I am using the latest version of Rollup and rollup-plugin-commonjs.

**Comment by airhorns** [comment]
@Rich-Harris this example is also still broken for me for requiring d3 version 3 from an npm module ... any suggestions? 

```
    "rollup": "^0.36.3",
    "rollup-plugin-commonjs": "^5.0.5",
```
